### ISSUE TITLE
obwrapper.cpp issue

### ISSUE THREAD

**Issue by telukir** [ergo70/pgchem_tigress#1]
I am getting a make error as following:

g++  -fPIC -O2 -finline-functions -funroll-loops -I. -Iopenbabel-2.3.2/build/include/ -Iopenbabel-2.3.2/include/ -Iopenbabel-2.3.2/include/openbabel/ -Iopenbabel-2.3.2/build/ -I../../../src/backend/  -I. -I. -I../../../src/include -D_GNU_SOURCE   -c -o obwrapper.o obwrapper.cpp
obwrapper.cpp:114:12: error: '_ISOTOPE_PATTERN' does not name a type
 extern "C" _ISOTOPE_PATTERN *
            ^
<builtin>: recipe for target 'obwrapper.o' failed
make: **\* [obwrapper.o] Error 1

This is coming in the file obrapper.cpp

`extern "C" _ISOTOPE_PATTERN *
ob_molfile_to_isotope_pattern(char *molfile, int charge, double normal)
{
    _ISOTOPE_PATTERN *retval;
    vector<double> msa_mz;
    vector<double> msa_abundance;
    vector<unsigned int> composition;
    vector<unsigned int> m;
    const double limit = 10e-30;
    OBMol mol;
    OBConversion conv;
    string tmpStr (molfile);
    istringstream molstream (tmpStr);
    double main_peak_mass=0.0, scale = 1.0, maxintensity;`

is it correct or what should be changed?

**Comment by ergo70** [comment]
No, this is not correct. I'll check.

**Comment by ergo70** [comment]
Hm, I just cloned the repository fresh from github, added OpenBabel 2.3.2 and compiled with 'make -f Makefile.linux.x64' - no errors.

_ISOTOPE_PATTERN is defined in obwrapper.h.
Wrong include path?
What is the command you are using to build?
